services:
  postgres:
    image: postgres:15
    container_name: dagestan-audio-guide-postgres
    environment:
      POSTGRES_DB: dagestan_audio_guide
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U strapi_user"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: